version: '2'
services:
  biologist-web:
    build:
      context: .
      dockerfile: Dockerfile-biologist-web
    ports:
      - "8080:8080"
    entrypoint:
      - python3
      - -m
      - http.server
    command: "8080"
    working_dir: /biologist-web
    depends_on:
      - biologistd
  biologistd:
    build:
      context: .
      dockerfile: Dockerfile-biologistd
    ports:
      - "8081:8081"
    entrypoint:
      - biologistd
    command: ["--port", "8081"]
    logging:
      driver: json-file
