version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-biologist-web
    ports:
     - "8080:8080"
    depends_on:
     - biologistd
  biologistd:
    build:
      context: .
      dockerfile: Dockerfile-biologistd
    ports:
     - "8081:8081"
